### ISSUE TITLE
Path separator not working on Linux

### ISSUE THREAD

**Issue by Pipodi** [space-commits/SPT-Realism-Mod-Server#40]
Hi,

I've installed this mod next to Stay In Tarkov mod, inside our Docker container on a Linux server. When I've installed this, we got this error: 

```
[Client Request] xx.xx.xx.xx \\RealismMod\GetInfo
Failed to read config file Error: ENOENT: no such file or directory, open '/opt/server/user/mods/undefined/config/config.json'
    at Object.readFileSync (node:fs:453:20)
    at Object.readFileSync (pkg/prelude/bootstrap.js:1079:36)
    at Object.action (/opt/server/user/mods/SPT-Realism-Mod-Server/src/mod.ts:158:53)
    at DynamicRouterMod.handleDynamic (/snapshot/src/di/Router.ts:65:61)
    at HttpRouter.handleRoute (/snapshot/src/routers/HttpRouter.ts:75:63)
    at HttpRouter.getResponse (/snapshot/src/routers/HttpRouter.ts:47:18)
    at AkiHttpListener.getResponse (/snapshot/src/servers/http/AkiHttpListener.ts:150:38)
    at AkiHttpListener.handle (/snapshot/src/servers/http/AkiHttpListener.ts:39:39)
    at HttpServer.handleRequest (/snapshot/src/servers/HttpServer.ts:103:26)
    at Server.<anonymous> (/snapshot/src/servers/HttpServer.ts:45:18) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/opt/server/user/mods/undefined/config/config.json'
}
[UNHANDLED][//RealismMod/GetInfo]
```

because the path separator on Linux is not "\", but"/".

The fix is pretty simple, I've tried this on my Linux installation:

line 155, mod.ts file, should be

```
const parsedPath = __dirname.split(path.sep);
```

With this change, this should work for both Linux and Windows servers. I would open a PR for this but I couldn't.

**Comment by space-commits** [comment]
SIT is not supported and not compatible

**Comment by Pipodi** [comment]
The SIT community just ported the client-side of this mod: https://github.com/Psychicbear/SIT-Realism-Mod-Client

The server files they use are those from this repo, I thought it would be nice to include these fix in the release, just because otherwise this mod doesn't work on Linux distributions.
